### ISSUE TITLE
2020-01-31 時点のドキュメントに更新

### ISSUE THREAD

**Issue by hnakamur** [lxc-jp/lxd-ja#124]
* [x] api-extensions.md
* [x] backup.md
* [x] cloud-init.md
* [x] clustering.md
* [x] configuration.md
* [x] daemon-behavior.md
* [x] database.md
* [x] debugging.md
* [x] dev-lxd.md
* [x] faq.md
* [x] image-handling.md
* [x] index.md
* [x] instances.md
* [x] migration.md
* [x] networks.md
* [x] production-setup.md
* [x] projects.md
* [x] rest-api.md
* [x] security.md
* [x] storage.md

**Comment by hnakamur** [comment]
多くは container -> instance, instance -> server の置き換えです。

**Comment by hnakamur** [comment]
upstream ブランチの変更内容を
```
git diff --color-words HEAD~
```
で見ていただくと確認しやすいと思います（私はこれで差分見ながら翻訳を更新しています）。

**Comment by hnakamur** [comment]
ちなみに日本語のほうは空白区切りではないので `git diff --color-words` だと変更前後の単語もある程度含まれてしまいます。
http://neos21.hatenablog.com/entry/2018/05/28/080000
を参考に `git diff --color-words=$'[^\x80-\xbf][\x80-\xbf]*'` を試してみたのですが、
coinstaincer や コインスタンテナス のように container → instance, コンテナ→インスタンスが 1 文字単位で差分表示されてしまい、惜しい、残念！という感じでした。

**Comment by tenforward** [comment]
たくさんの更新を一気に更新いただいてありがとうございました。おつかれさまでした！

**Comment by hnakamur** [comment]
こちらこそ、たくさんレビューしていただきありがとうございました！
