### ISSUE TITLE
configuration.mdのオリジナルのコメント方法

### ISSUE THREAD

**Issue by tenforward** [lxc-jp/lxd-ja#23]
configuration.md で箇条書きの部分を一括でコメントにしていますが、Read the docs で見ると表示が変になっていますね。

http://lxd-ja.readthedocs.io/ja/latest/configuration/

**Comment by hnakamur** [comment]
すみません、確認不足でした。ご指摘ありがとうございます。
プルリク #24 を作ったので確認お願いします。

**Comment by tenforward** [comment]
ありがとうございました。github では正常に見えているのでわからないですものね。
