### ISSUE TITLE
titleの中のコメント

### ISSUE THREAD

**Issue by znz** [lxc-jp/lxd-ja#64]
Google の検索結果のタイトルにコメントっぽい部分が含まれていて気づいたのですが、たとえば https://lxd-ja.readthedocs.io/ja/latest/containers/ で
`<title>コンテナの設定 <!-- Container configuration --> - LXDドキュメント翻訳プロジェクト</title>`
となっていて title 要素にコメントが含まれていて、[昔はコメントとして扱われる仕様だったのにそうなっていないブラウザがあった](http://bakera.jp/ref/html/element/title)のが、[HTML5では実装に合わせてコメントとして扱われなくなった](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inhead)という[ことらしい](https://twitter.com/bakera/status/1083256403194654720)ので、原文をコメントとして残すなら、別の行にするなどの対処をした方が良さそうです。

**Comment by tenforward** [comment]
ありがとうございます。また見直します。

**Comment by tenforward** [comment]
この Issue は、一旦 #65 が終わったあとに考えましょう

**Comment by tenforward** [comment]
https://github.com/lxc-jp/lxd-ja/pull/72

**Comment by tenforward** [comment]
解決しました。
