### ISSUE TITLE
LXD 3.9 時点のドキュメントに更新

### ISSUE THREAD

**Issue by tenforward** [lxc-jp/lxd-ja#65]
更新分を翻訳
* https://github.com/lxc-jp/lxd-ja/commit/9adfc2559619f400b2a386408eae9ead2bb2b56c

- [x] api-extensions.md
- [x] clustering.md
- [x] containers.md
- [x] image-handling.md
- [x] index.md
- [x] projects.md
- [x] rest-api.md
- [x] security.md
- [x] server.md

**Comment by tenforward** [comment]
image-handling.md やります

**Comment by tenforward** [comment]
image-handling.md は小さい修正だったのでそのまま commit & push しておきました

**Comment by hnakamur** [comment]
rest-api.md も例のjsonが変わっているだけなので commit & push しておきました。

**Comment by hnakamur** [comment]
server.md やります。

**Comment by hnakamur** [comment]
security.md やります。

**Comment by hnakamur** [comment]
projects.md やります。

**Comment by hnakamur** [comment]
api-extensions.md やります。

**Comment by tenforward** [comment]
index.md やります。

**Comment by tenforward** [comment]
index.md はリンク先の変更と翻訳不要な部分の更新でしたのでそのまま commit & push しておきました。

**Comment by hnakamur** [comment]
containers.md やります。

**Comment by hnakamur** [comment]
clustering.md やります。

**Comment by tenforward** [comment]
@hnakamur おつかれさまでした&ありがとうございました！マージしました。ほぼすべてやっていただきましたね 😄
